### ISSUE TITLE
Generated photoshop gradient file is incorect?

### ISSUE THREAD

**Issue by mazznoer** [eltos/gradient#1]
**To Reproduce**
1. Create random gradient
2. Save as photoshop gradient file.
3. Open the downloaded file using [this online gradient viewer](http://hi104.github.io/psd-grd/)
4. Nothing is shown

**Stack Trace**
```
If applicable, paste the full stack trace as found in your browsers console (F12) here
```

**Screenshots**
Add screenshots to help explain the issue

**Environment**
- OS: Ubuntu
- Browser and version: Firefox 114.0.1
- Git revision

**Comment by eltos** [comment]
My tool produces version 3 GRC files as specified here:  
http://www.selapa.net/swatches/gradients/fileformats.php

From a quick look at the project you linked it looks like that project assumes GRC files of version 5, but it seams not to check for the actual GRC version of the uploaded file and thus fails silently.

I don't understand why you want to use that tool to convert the GRC file into CSS or SVG, when instead you could just use the CSS or SVG produced by my tool in the first place. If there is some reason, I suggest contacting the other project's maintainer and asking for support of version 3 GRC files.
